### ISSUE TITLE
Alloy Metal Block layers over Alloy Panel

### ISSUE THREAD

**Issue by ChangelingRain** [Unknown-Anomaly/Peglaci#41]
![](http://puu.sh/BMyVt/c85c778648.png)
It used to be the other way around.

**Comment by GonDragon** [comment]
I changed it to be that way when I updated the materials (previously, no material had a defined zLevel, so how interact between them and with vanilla blocks were kinda random).

I tough it looked better that way, but I don't use Aloy Panels a lot in constructions. So, Do you think that it's better how it used to be?

**Comment by ChangelingRain** [comment]
Yeah, I do; it pops more and draws the eye better that way.

A slight note on the zlevel thing:
If materials have the same zlevel, it substitutes the id instead, with higher ids layering higher than other materials on the same zlevel—which is why the zlevels for peglaci blocks are all over the place; the material id was chosen for layering instead of properly using the zlevel var.

Anyway since I'm bored and have an idea of how to fix this in a way that looks good I'm gonna make a PR in a bit.

**Comment by ChangelingRain** [comment]
I do, yeah; it pops better and has a better look.

A side note on zlevels:
Peglaci blocks(improperly, and it must have been a pain to do!) use their material ID as their layer, since materials on the same layer will put the material with the higher ID value higher—which is why their material IDs are all over the place, relatively.

I'm gonna make a PR to fix this specific thing+adjust overall with that information in mind.

**Comment by GonDragon** [comment]
Cool. I sugest that the best choice is to raise the zLevel of the Alloy Panel to be the same as the Metal Block, as I assigned the zLevels thinking on how the blocks will interact with vanilla tiles.

If you don't make the PR, I will make the change myself and push it to Steam this weekend.
